apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-web
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: statefulset
    name: web
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 10