apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "web-ing"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    kubernetes.io/cluster.name: Devil
  labels:
    app: web
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: "my-service"
              servicePort: 80

