apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: "nginx"
  replicas: 2
  selector:
    matchLabels:
      app:  web
  template:
    metadata:
      labels:
        app:  web
    spec:
      containers:
      - name: nginx
        image: sumanthc/node-js_routes:latest
        ports:
        - containerPort: 3000
          name: web

    
  